//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BHYT
    {
        public string MaBHYT { get; set; }
        public Nullable<System.DateTime> NgayBDBHYT { get; set; }
        public Nullable<System.DateTime> NgayHHBHYT { get; set; }
        public string QueQuan { get; set; }
    }
}
