//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DieuTri
    {
        public System.DateTime NgayDieuTri { get; set; }
        public System.DateTime NgayXuatVien { get; set; }
        public string MaBN { get; set; }
        public string MaNV { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
