//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonThuoc
    {
        public string MaDT { get; set; }
        public string TenDT { get; set; }
        public string CachSuDung { get; set; }
        public Nullable<int> DonViTinh { get; set; }
    }
}
