//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MacBenh
    {
        public string MaBN { get; set; }
        public string MaLB { get; set; }
        public System.DateTime ThoiGianMacBenh { get; set; }
    
        public virtual BenhNhan BenhNhan { get; set; }
        public virtual LoaiBenh LoaiBenh { get; set; }
    }
}
