//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyBenhNhan
{
    using System;
    using System.Collections.Generic;
    
    public partial class Thuoc
    {
        public string MaThuoc { get; set; }
        public string TenThuoc { get; set; }
    }
}
